{% set name = "aws-glue-sessions" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-glue-sessions-{{ version }}.tar.gz
  sha256: 1dd639e7826158d9c842b0dc1dab504b9e79d25cc076ced8e5cd48c78f7c20f1

build:
  entry_points:
    - install-glue-kernels = aws_glue_interactive_sessions_kernel.glue_kernel:install
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - hdijupyterutils >=0.6
    - autovizwidget >=0.6
    - ipython >=4.0.2
    - nose
    - requests
    - ipykernel >=6.12.1
    - ipywidgets >5.0.0
    - notebook >=4.2
    - tornado >=4
    - boto3 >=1.21.31
    - botocore >=1.24.24
    - click
    - importlib-metadata >=4.11.3
    - rich
    - tabulate

test:
  imports:
    - aws_glue_interactive_sessions_kernel
  commands:
    - pip check
    - install-glue-kernels --help
  requires:
    - pip

about:
  home: https://aws.amazon.com/glue/
  summary: Glue Interactive Sessions Jupyter kernel that integrates almost anywhere Jupyter does including your favorite IDEs.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - just4brown
